### ISSUE TITLE
Wiki Edit History Of User page broken

### ISSUE THREAD

**Issue by scrimpeh** [adelikat/tasvideos#382] opened 2021-09-03 10:31 UTC
See https://tasvideos.mistflux.net/Wiki/EditHistory/scrimpeh

I tried setting up a local development environment with a MSSQL database, but couldn't reproduce it, unfortunately.

**Comment by nattthebear** [comment] 2021-09-03 11:29
Duplicate of #379

**Closed by nattthebear** 2021-09-03 11:29 UTC
